apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: mach-k8s-devenv-controller
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
