name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint codebase
    runs-on: [self-hosted, nix]
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Run linter
        run: nix develop --command just lint

      - name: Run formatter
        run: nix develop --command just format
